module.exports = [
  {
    "name": "Login Screen",
    "path": "/#/login",
    "testCases": [
      "Verify successful login with valid credentials",
      "Verify error message with invalid email format",
      "Verify error message with incorrect password",
      "Verify password field masks input by default",
      "Verify toggle password visibility works",
      "Verify Forgot Password link redirects correctly",
      "Verify Register Here link redirects to registration",
      "Verify login button disabled when fields are empty",
      "Verify login with unregistered email",
      "Verify loading spinner appears during login request",
      "Verify successful login redirects to Dashboard",
      "Verify session token is stored after login",
      "Verify Remember Me checkbox functionality",
      "Verify session persistence across tabs",
      "Verify login via Google SSO",
      "Verify login via Apple SSO",
      "Verify login via Facebook SSO",
      "Verify account lockout after 5 failed attempts",
      "Verify Enter key submits the login form",
      "Verify validation errors clear on input change",
      "Verify UI responsiveness on mobile viewport",
      "Verify accessibility tab order on login form",
      "Verify login API timeout handling",
      "Verify back button behavior after login",
      "Verify input sanitization on login fields"
    ]
  },
  {
    "name": "Register Screen",
    "path": "/#/register",
    "testCases": [
      "Verify successful registration with valid data",
      "Verify error on existing email address",
      "Verify password strength indicator",
      "Verify password mismatch error in confirmation field",
      "Verify terms and conditions checkbox validation",
      "Verify email format validation",
      "Verify registration button disabled until fields filled",
      "Verify OTP sent after registration submission",
      "Verify resend OTP functionality",
      "Verify successful OTP verification redirects to home",
      "Verify invalid OTP error handling",
      "Verify registration via Google SSO",
      "Verify registration via Apple SSO",
      "Verify phone number formatting and validation",
      "Verify optional fields can be left blank",
      "Verify profile picture upload during registration",
      "Verify max file size for profile picture",
      "Verify supported formats for profile picture",
      "Verify UI responsiveness on tablet viewport",
      "Verify accessibility contrast ratios",
      "Verify keyboard navigation through form",
      "Verify error messages are screen-reader accessible",
      "Verify back button returns to login screen",
      "Verify loading state during registration API call",
      "Verify secure transmission of password (HTTPS)"
    ]
  },
  {
    "name": "Dashboard Screen",
    "path": "/#/dashboard",
    "testCases": [
      "Verify Dashboard loads correctly after authentication",
      "Verify user profile summary is displayed",
      "Verify recent activity feed loads",
      "Verify quick action buttons are clickable",
      "Verify unread notifications count is accurate",
      "Verify clicking notification opens details",
      "Verify navigation drawer opens and closes",
      "Verify search functionality returns results",
      "Verify empty state when no activity exists",
      "Verify dashboard statistics match backend data",
      "Verify pull-to-refresh updates dashboard data",
      "Verify infinite scrolling on activity feed",
      "Verify lazy loading of images on dashboard",
      "Verify dashboard handles offline mode gracefully",
      "Verify dashboard UI on large desktop screens",
      "Verify theme toggle applies dark mode",
      "Verify theme toggle applies light mode",
      "Verify language selector updates dashboard text",
      "Verify logout button on dashboard works",
      "Verify back button exits app from dashboard"
    ]
  },
  {
    "name": "Profile Screen",
    "path": "/#/profile",
    "testCases": [
      "Verify user details are loaded correctly",
      "Verify Edit Profile button enables form fields",
      "Verify saving profile updates backend data",
      "Verify canceling edit restores original data",
      "Verify name field validation (no special chars)",
      "Verify bio character limit enforcement",
      "Verify profile picture can be changed",
      "Verify camera opens for new profile picture",
      "Verify gallery opens for profile picture selection",
      "Verify cropping functionality for profile picture",
      "Verify email update requires re-authentication",
      "Verify password change from profile screen",
      "Verify password change requires current password",
      "Verify delete account button opens confirmation",
      "Verify account deletion permanently removes user",
      "Verify privacy settings toggle switches",
      "Verify notification preferences save correctly",
      "Verify two-factor authentication toggle",
      "Verify 2FA setup process completes",
      "Verify linked accounts section displays integrations",
      "Verify unlinking a Google account works",
      "Verify download personal data feature",
      "Verify UI breaks on extremely long names",
      "Verify timezone setting updates properly",
      "Verify profile screen load time under 2 seconds"
    ]
  },
  {
    "name": "Settings Screen",
    "path": "/#/settings",
    "testCases": [
      "Verify settings screen loads sections correctly",
      "Verify app version is displayed at bottom",
      "Verify clear cache button frees storage",
      "Verify push notifications global toggle",
      "Verify email notifications global toggle",
      "Verify SMS notifications global toggle",
      "Verify data usage settings (Wi-Fi only mode)",
      "Verify auto-play video settings",
      "Verify location permissions toggle",
      "Verify camera permissions toggle",
      "Verify microphone permissions toggle",
      "Verify contact sync functionality",
      "Verify default language selection",
      "Verify default currency selection",
      "Verify measurement unit toggle (Metric/Imperial)",
      "Verify help and support link opens webview",
      "Verify terms of service link opens webview",
      "Verify privacy policy link opens webview",
      "Verify open source licenses view",
      "Verify report a bug form submission",
      "Verify rate app redirects to app store",
      "Verify developer mode hidden menu",
      "Verify beta features opt-in toggle",
      "Verify account limits and quotas view",
      "Verify sign out from all devices functionality"
    ]
  },
  {
    "name": "Analyze Screen",
    "path": "/#/analyze",
    "testCases": [
      "Verify analyze screen requires camera access",
      "Verify analyze engine starts up correctly",
      "Verify real-time analysis overlay renders",
      "Verify object detection bounding boxes appear",
      "Verify confidence score is displayed",
      "Verify analysis pauses when app backgrounded",
      "Verify analysis resumes when app foregrounded",
      "Verify flashlight toggle during analysis",
      "Verify camera flip (front/back) functionality",
      "Verify zoom functionality during analysis",
      "Verify analysis handles poor lighting conditions",
      "Verify analysis handles blurry images",
      "Verify fast-moving object tracking",
      "Verify multiple object detection simultaneously",
      "Verify capture button snaps current frame",
      "Verify analyze history logs current session",
      "Verify AI model version is visible",
      "Verify offline analysis mode functionality",
      "Verify thermal/depth sensor toggle if available",
      "Verify analysis stops gracefully on exit",
      "Verify memory usage during prolonged analysis",
      "Verify battery consumption warning",
      "Verify error when camera hardware fails",
      "Verify unsupported device error message",
      "Verify save analysis metadata to local DB"
    ]
  },
  {
    "name": "Chatbot Screen",
    "path": "/#/chatbot",
    "testCases": [
      "Verify chatbot screen loads conversation history",
      "Verify new message input field works",
      "Verify send button disabled on empty input",
      "Verify typing indicator appears when bot processes",
      "Verify bot responds with text",
      "Verify bot responds with rich media (images)",
      "Verify bot responds with action buttons",
      "Verify clicking action button sends payload",
      "Verify timestamp on messages is correct",
      "Verify user messages align right",
      "Verify bot messages align left",
      "Verify scroll to bottom on new message",
      "Verify pull down loads older messages",
      "Verify quick reply chips disappear after use",
      "Verify voice input to text translation",
      "Verify clear chat history functionality",
      "Verify export chat transcript",
      "Verify chatbot handles network disconnect",
      "Verify chatbot handles session timeout",
      "Verify swear word filter on user input",
      "Verify bot fallback message on unknown intent",
      "Verify rating prompt after conversation",
      "Verify minimize chatbot widget",
      "Verify unread message badge on widget",
      "Verify copy message text to clipboard"
    ]
  },
  {
    "name": "History Screen",
    "path": "/#/history",
    "testCases": [
      "Verify history list loads from local DB",
      "Verify chronological sorting of history items",
      "Verify grouping history by date",
      "Verify pull-to-refresh syncs cloud history",
      "Verify clicking history item opens details",
      "Verify delete individual history item",
      "Verify swipe-to-delete history item",
      "Verify bulk delete multiple history items",
      "Verify clear all history opens warning",
      "Verify search history by keyword",
      "Verify filter history by category",
      "Verify filter history by date range",
      "Verify empty state illustration when no history",
      "Verify pagination/infinite scroll on large history",
      "Verify export history to CSV"
    ]
  },
  {
    "name": "Capture Screen",
    "path": "/#/capture",
    "testCases": [
      "Verify capture screen initializes camera quickly",
      "Verify grid overlay toggle",
      "Verify aspect ratio toggle (1:1, 4:3, 16:9)",
      "Verify timer functionality (3s, 10s)",
      "Verify flash modes (Auto, On, Off)",
      "Verify HDR toggle functionality",
      "Verify shutter button snaps photo",
      "Verify burst mode on holding shutter",
      "Verify video recording starts on long press",
      "Verify preview thumbnail updates after capture",
      "Verify clicking thumbnail opens gallery",
      "Verify auto-focus on tap",
      "Verify exposure slider adjustment",
      "Verify capture fails gracefully if storage full",
      "Verify location tagging (EXIF) on capture"
    ]
  },
  {
    "name": "Match Checker Screen",
    "path": "/#/match-checker",
    "testCases": [
      "Verify match checker takes two inputs",
      "Verify input A selection from gallery",
      "Verify input B selection from camera",
      "Verify run match algorithm button",
      "Verify progress bar during matching",
      "Verify match percentage score is displayed",
      "Verify detailed match breakdown chart",
      "Verify matching highlights differences",
      "Verify matching highlights similarities",
      "Verify save match result functionality",
      "Verify share match result via native sheet",
      "Verify error when inputs are incompatible",
      "Verify 3D model matching view",
      "Verify AR overlay of matched items",
      "Verify reset match checker clears inputs"
    ]
  },
  {
    "name": "Shop Screen",
    "path": "/#/shop",
    "testCases": [
      "Verify shop catalog loads products",
      "Verify product categories horizontal scroll",
      "Verify product card displays price and image",
      "Verify clicking product opens details page",
      "Verify add to cart button animates",
      "Verify cart badge increments",
      "Verify wishlist heart toggle",
      "Verify sort by price (Low to High)",
      "Verify filter by size and color",
      "Verify search products by name",
      "Verify out of stock items are grayed out",
      "Verify product image carousel swipe",
      "Verify reading product reviews",
      "Verify writing a product review",
      "Verify related products section"
    ]
  },
  {
    "name": "Recommended Colors Screen",
    "path": "/#/recommended-colors",
    "testCases": [
      "Verify color palette generation based on profile",
      "Verify primary color hex code is visible",
      "Verify secondary color hex code is visible",
      "Verify accent color hex code is visible",
      "Verify tap to copy hex code to clipboard",
      "Verify color blind simulation view",
      "Verify save palette to favorites",
      "Verify share palette as image",
      "Verify applying palette to app theme preview",
      "Verify color harmony rule selection (Analogous)",
      "Verify color harmony rule selection (Complementary)",
      "Verify extract colors from uploaded image",
      "Verify contrast ratio checker passes",
      "Verify seasonal color recommendations",
      "Verify trending colors API integration"
    ]
  },
  {
    "name": "Analysis Result Screen",
    "path": "/#/analysis-result",
    "testCases": [
      "Verify result screen displays source image",
      "Verify main detected entity title",
      "Verify confidence score gauge chart",
      "Verify detailed attributes list",
      "Verify actionable recommendations based on result",
      "Verify export result to PDF",
      "Verify share result link generation",
      "Verify flag result as incorrect (Feedback loop)",
      "Verify related articles/knowledge base links",
      "Verify 3D visualization of result if applicable",
      "Verify compare with previous results",
      "Verify save to specific project folder",
      "Verify delete result from database",
      "Verify print result via system dialog",
      "Verify result metadata (time, location, device)"
    ]
  },
  {
    "name": "Splash Screen",
    "path": "/",
    "testCases": [
      "Verify splash screen displays app logo",
      "Verify splash screen animates correctly",
      "Verify splash screen hides status bar",
      "Verify background color matches theme",
      "Verify splash screen lasts minimum 1 second",
      "Verify app routing checks authentication state",
      "Verify auto-login routes to Dashboard",
      "Verify unauthenticated routes to Login",
      "Verify first-time launch routes to Onboarding",
      "Verify deep link routing intercepts splash",
      "Verify forced app update check during splash",
      "Verify maintenance mode check during splash",
      "Verify network availability check",
      "Verify local database migration runs",
      "Verify splash screen on cold start",
      "Verify splash screen on warm start",
      "Verify error boundary catches startup crashes",
      "Verify analytics SDK initializes",
      "Verify crash reporting SDK initializes",
      "Verify push notification token refresh",
      "Verify localization strings load",
      "Verify custom fonts load before routing",
      "Verify theme preference loads before routing",
      "Verify splash screen is accessible (aria-hidden)",
      "Verify splash screen memory footprint",
      "Verify splash screen on slow network",
      "Verify splash timeout fallback",
      "Verify offline mode routing",
      "Verify caching of static assets",
      "Verify root component mounts successfully",
      "Verify redux store hydration",
      "Verify global interceptors setup",
      "Verify WebSocket connection initiated",
      "Verify biometric prompt triggers if enabled",
      "Verify permission requests deferred until needed",
      "Verify splash screen resolution on 4K displays",
      "Verify splash screen on notch devices",
      "Verify system dark mode override",
      "Verify system font scaling affects logo",
      "Verify landscape orientation handles splash correctly"
    ]
  }
];